name: wilt
version: 3.2.0
author: S. Hamblett <steve.hamblett@linux.com>
description: A browser/server based  CouchDB library
homepage: https://github.com/shamblett/wilt
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dependencies:
  browser: any
  crypto: '>=0.9.0 <0.9.1'
  http: '>=0.11.3+2'
  json_object: '>=1.0.15'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
