name: wilt
version: 4.0.0
author: S. Hamblett <steve.hamblett@linux.com>
description: A browser/server based  CouchDB library
homepage: https://github.com/shamblett/wilt

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  crypto: '>=2.0.1 <3.0.0'
  http: '>=0.11.3+13'
  json_object_lite: '^2.0.0'

dev_dependencies:
  test: '^1.3.0'
  coverage: '^0.12.2'
  #dart_dev: '^2.0.0-alpha'
  dart_style: '^1.1.3'
  dartdoc: '^0.20.3'
  build_runner: '^0.10.0'
  build_test: '^0.10.2'
  build_web_compilers: '^0.4.0'
