name: wilt
version: 3.4.0
author: S. Hamblett <steve.hamblett@linux.com>
description: A browser/server based  CouchDB library
homepage: https://github.com/shamblett/wilt

environment:
  sdk: '>=1.0.0 <2.0.0-dev.infinity'

dependencies:
  browser: any
  crypto: '>=2.0.1 <3.0.0'
  cryptoutils: '>=0.2.1 <=3.0.0'
  http: '>=0.11.3+13'
  json_object_lite: '>=1.0.0 <=2.0.0'

dev_dependencies:
    test: '^0.12.0'
    coverage: '^0.7.3'
    dart_dev: '^1.0.0'
    dart_style: '>=0.2.0 <0.3.0'
    dartdoc: '>=0.8.0 <=0.10.0'

web:
  compiler:
    debug: dartdevc

transformers:
- test/pub_serve:
    $include: test/wilt_test_browser.dart