name: wilt
version: 3.0.0
author: S. Hamblett <steve.hamblett@linux.com>
description: A browser/server based  CouchDB API  library based on the SAG CouchDB library for PHP
homepage: https://github.com/shamblett/wilt
environment:
  sdk: '>=0.8.10+6 <2.0.0'
documentation: http://oscf.org.uk/dart/api/wilt/index.html
dependencies:
  browser: '>=0.5.20 <0.5.21'
  crypto: '>=0.9.0 <0.9.1'
  http: '>=0.9.2+3 <0.9.3'
  json_object: '>=1.0.15'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
